DROP DATABASE IF EXISTS HotelManagementDB;
CREATE DATABASE HotelManagementDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE HotelManagementDB;
CREATE TABLE Guest (
    GuestID INT PRIMARY KEY AUTO_INCREMENT,
    GuestName VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
    Address VARCHAR(200) CHARACTER SET utf8mb4,
    Email VARCHAR(100) CHARACTER SET utf8mb4 UNIQUE
);
CREATE TABLE Room (
    RoomID INT PRIMARY KEY AUTO_INCREMENT,
    RoomType VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL,
    PricePerNight DECIMAL(10,2) NOT NULL
);
CREATE TABLE Reservation (
    ReservationID INT PRIMARY KEY AUTO_INCREMENT,
    GuestID INT NOT NULL,
    RoomID INT NOT NULL,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE,
    FOREIGN KEY (GuestID) REFERENCES Guest(GuestID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW tables;

