--thuc the . Khachhang(MaKH(PK).TenKH.EMAIL).
--DONHANG( MaDH(PK).MaKH(FK-KHACHHANG-MAKH).NGAYDAT.
--SP(MASP(PK).TENSP.GIA.
--CHITIETDONHANG(MACT(PK).MADH(FK-DH VA MADH).MASP(FK-SANPHAM VA MASP). SOLUONG;

CREATE DATABASE ThuongMaiDienTu;
USE ThuongMaiDienTu;
CREATE TABLE KhachHang (
MaKH INT PRIMARY KEY,
TenKH VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL);
CREATE TABLE SanPham (
MaSP INT PRIMARY KEY,
TenSP VARCHAR(100) NOT NULL,
Gia DECIMAL(10,2) NOT NULL);
CREATE TABLE DonHang (
MaDH INT PRIMARY KEY,
MaKH INT,
NgayDat DATE NOT NULL,
FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH));
CREATE TABLE ChiTietDonHang (
MaCT INT PRIMARY KEY,
MaDH INT,
MaSP INT,
SoLuong INT NOT NULL,
FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
FOREIGN KEY (MaSP) REFERENCES SanPham (MaSP));
DROP TABLE ChiTietDonHang;
--CHEN DU LIEU MAU
--KHACH HANG
INSERT INTO KhachHang (MaKH, TenKH, Email)
VALUES
(1, 'Pham Thi Huyen', 'huyen@gmail.com'),
(2, 'Pham Thi Trang', 'trang@gmail.com');
SELECT * FROM KhachHang;
-san pham
INSERT INTO SanPham (MaSP, TenSP, Gia) VALUES
(100, 'Banh in', 50000),
(101, 'Nuoc trai cay', 10000);
---don hang
INSERT INTO DonHang (MaDH, MaKH, NgayDat) VALUES
(1000, 1, '2025-11-14'),
(1001, 2, '2025-12-10');
---CHI TIET DON HANG
INSERT INTO ChiTietDonHang (MaCT, MaDH, MaSP, SoLuong) VALUES
(1, 1000, 100, 4),
(2, 1001, 101, 10);








